### ISSUE TITLE
CI failed and doesn't find the multiqc file anymore

### ISSUE THREAD

**Issue by Zethson** [laminlabs/snakemake-lamin-usecases#4]
https://github.com/laminlabs/snakemake-lamin-usecases/actions/runs/6248584656/job/16963502662

**Comment by falexwolf** [comment]
Same thing seems to have happened on the nextflow notebook just now, but not for Sunny's PR.

**Comment by falexwolf** [comment]
https://github.com/laminlabs/nextflow-lamin-usecases/issues/15

**Comment by Zethson** [comment]
I re triggered the CI earlier and it fixed itself.

Sep 20, 2023 7:08:10 PM Alex Wolf ***@***.***>:
